name: Deploy Staging MMU

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy_staging:
    name: Deploy Staging MMU
    uses: ./.github/workflows/deploy-mmu.yml
    with:
      env: "staging"
      ecr_url: "677285201534.dkr.ecr.ap-northeast-1.amazonaws.com"
      ecr_repo_name: "staging-market-map-updater"
    secrets:
      aws_access_key_id: ${{ secrets['STAGING_MARKET_MAP_UPDATER_AWS_ACCESS_KEY_ID'] }}
      aws_secret_access_key: ${{ secrets['STAGING_MARKET_MAP_UPDATER_AWS_SECRET_ACCESS_KEY'] }}
